export const GET_ALL_PROVIDERS_ACTION = 'GET_ALL_PROVIDERS_ACTION';
export const ADD_PROVIDER_ACTION ='ADD_PROVIDER_ACTION';
export const UPDATE_PROVIDER_ACTION ='UPDATE_PROVIDER_ACTION';
export const DELETE_PROVIDER_ACTION ='DELETE_PROVIDER_ACTION';