export const GET_ALL_AUTHORITIES_ACTION = 'GET_ALL_AUTHORITIES_ACTION';
export const DELETE_AUTHORITIES_ACTION ='DELETE_AUTHORITIES';
export const ADD_AUTHORITIES_ACTION = 'ADD_AUTHORITIES';

export const GET_ALL_ROLES_ACTION = 'GET_ALL_ROLES_ACTION';
export const GET_ALL_USERS_ACTION = 'GET_ALL_USERS_ACTION';
