export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILED = 'CHECKOUT_FAILED';

export const THEM_GIO_HANG = 'THEM_GIO_HANG';
export const XOA_GIO_HANG = 'XOA_GIO_HANG';
export const XOA_GIO_HANG_MASP = 'XOA_GIO_HANG_MASP';
export const TANG_GIAM_SL = 'TANG_GIAM_SL';

export const GET_ALL_ROLES = 'GET_ALL_ROLES';
export const GET_ALL_AUTHORITIES = 'GET_ALL_AUTHORITIES';
export const GET_ALL_USERS = 'GET_ALL_USERS';

export const HIDE_LOADING = 'HIDE_LOADING';
export const DISPLAY_LOADING = 'DISPLAY_LOADING';

export const DELETE_AUTHORITIES= 'DELETE_AUTHORITIES';
export const ADD_AUTHORITIES = 'ADD_AUTHORITIES';

export const GET_ALL_PROVIDERS = 'GET_ALL_PROVIDERS';
export const ADD_PROVIDER = 'ADD_PROVIDER';
export const UPDATE_PROVIDER ='UPDATE_PROVIDER';
export const DELETE_PROVIDER ='DELETE_PROVIDER';