server:
  error:
    path: /error
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345
    url: jdbc:mysql://localhost:3306/MiniStore
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: false
  mail:
    default-encoding: UTF-8
    host: smtp.googlemail.com
    password: longlong66
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000
    username: longtpc01189@fpt.edu.vn
  main:
    allow-bean-Definition-overriding: true
  security:
      oauth2:
        client:
          registration:
            google:
              clientId: 936587726373-friqii83r96m700i1cg8vm167quiln40.apps.googleusercontent.com
              clientSecret: gYObxhfpgr98xC_4rO3OQTDZ
#              redirectUri: "http://localhost:8080/oauth2/callback/936587726373-friqii83r96m700i1cg8vm167quiln40.apps.googleusercontent.com"
              scope:
                - email
                - profile
            facebook:
              clientId: 4148716035221644
              clientSecret: 1cdb94765d888358ed7aa9c6325296fe
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}" # Note that facebook now mandates the use of https redirect URIs, so make sure your app supports https in production
              scope:
                - email
                - public_profile
          provider:
            facebook:
              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
  
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: 20MB
      max-request-size: 20MB
