export const GET_ALL_USERS_MANAGER_ACTION = 'GET_ALL_USERS_MANAGER_ACTION';
export const GET_USER_BY_USERNAME_ACTION = 'GET_USER_BY_USERNAME_ACTION';
export const ADD_USER_ACTION = 'ADD_USER_ACTION';
export const UPDATE_USER_ACTION ='UPDATE_USER_ACTION';
export const DELETE_USER_ACTION ='DELETE_USER_ACTION';
export const LOGOUT_ACTION = 'LOGOUT';
export const LOGIN_ACTION = 'LOGIN_ACTION';